<?php

use Drupal\Core\Routing\RouteMatchInterface;

function aen_tools_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.aen_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Products Comparison') . '</p>';
      return $output;

    default:
  }
}

// Implements hook_theme()
function aen_tools_theme( $existing, $type, $theme, $path ){
    return [
        'aen_tools-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'aen_tools', // My template file name
            'variables' => [
                'site_name' => "sios-svalbard.org",
                'tiles' => null,
                'helptext' => '',
              ],
        ],
    ];
}


function aen_tools_leaflet_map_info_alter(&$map_info) {
    foreach ($map_info as $map_id => $info) {
      $map_info[$map_id]['settings']['zoom'] = 10;
      $map_info[$map_id]['label'] += ' ' . t('default yr zoom=2');
    }
  }
