<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;


function aen_tools_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
    // Main module help for the metsis_search module.
    /** TODO: Read help from module's README.md */
    case 'help.page.aen_tools':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Products Comparison') . '</p>';
      return $output;

    default:
  }
}

// Implements hook_theme()
function aen_tools_theme( $existing, $type, $theme, $path ){
    return [
        'aen_tools-template' => [
            'render element' => 'container', // To render a simple container element
            'template' => 'aen_tools', // My template file name
            'variables' => [
                'site_name' => "sios-svalbard.org",
                'tiles' => null,
                'helptext' => '',
              ],
        ],
    ];
}


/**
 * Implements hook_views_pre_render().
 *
 * Adding  our custom css to the AeN search views.
 */
function aen_tools_views_pre_render(ViewExecutable $view) {
  if (isset($view) && (($view->storage->id() == 'aen_stations') || ($view->storage->id() == 'aen_search'))) {
    $view->element['#attached']['library'][] = 'aen_tools/aen';
  }
}